export const ROUTES = {
    HOME: '/',
    CATALOG: '/catalog',
    SEARCH: '/search',
    PRODUCT: (id) => `/product/${id}`,
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
    CHECKOUT: '/checkout',
    ORDERS: '/orders',
    ORDER_TRACKING: (id) => `/orders/${id}/track`,
    WALLET: '/wallet',
    MY_ACCOUNT: '/my-account',
    ACCOUNT_SETTINGS: '/account/settings',
    INVOICES: '/invoices',
    QUICK_ORDER: '/quick-order',
    ADMIN: '/admin',
    ABOUT: '/about',
    PRIVACY: '/privacy',
    CAREERS: '/careers',
    SERVICES: '/services',
    NEWS_BLOG: '/news-blog',
    HELP_CENTER: '/help-center',
    MOBILE_APP: '/mobile-app',
    SHIPPING: '/shipping',
    RETURNS: '/returns',
    CONTACT_US: '/contact-us',
    BECOME_SELLER: '/become-seller',
    GIFT_CARDS: '/gift-cards',
    CATEGORY: (name) => `/category/${name}`,
    BRAND: (name) => `/brand/${name}`,
};
